# Generated by Django 5.2.1 on 2025-10-01 20:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SesionEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título descriptivo del plan de entrenamiento', max_length=200, verbose_name='Título del Entrenamiento')),
                ('descripcion', models.TextField(help_text='Puedes usar HTML simple para formatear. Por ejemplo: &lt;strong&gt;texto en negrita&lt;/strong&gt;, &lt;br&gt; para saltos de línea.', verbose_name='Descripción Detallada')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, help_text='El entrenamiento se considerará para activación a partir de esta fecha y hora.', verbose_name='Fecha y Hora de Publicación')),
                ('es_activo', models.BooleanField(default=False, help_text='Este campo se actualiza automáticamente basado en la fecha de publicación. El más reciente con fecha cumplida será el activo.', verbose_name='¿Es el entrenamiento activo actualmente?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Sesión de Entrenamiento',
                'verbose_name_plural': 'Sesiones de Entrenamiento',
                'ordering': ['-fecha_publicacion'],
                'indexes': [models.Index(fields=['es_activo', 'fecha_publicacion'], name='entrenamien_es_acti_f85134_idx'), models.Index(fields=['fecha_publicacion'], name='entrenamien_fecha_p_e74c88_idx')],
            },
        ),
    ]
