# Generated by Django 5.2.1 on 2025-05-16 20:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Entrenamiento')),
                ('descripcion', models.TextField(help_text='Puedes usar HTML simple para formatear.', verbose_name='Descripción Detallada')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Publicación')),
                ('es_activo', models.BooleanField(default=True, help_text='Marca esta casilla si este es el entrenamiento que se debe mostrar actualmente a los usuarios.', verbose_name='Es el entrenamiento activo')),
            ],
            options={
                'verbose_name': 'Sesión de Entrenamiento',
                'verbose_name_plural': 'Sesiones de Entrenamiento',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.DeleteModel(
            name='Entrenamiento',
        ),
    ]
