# Generated by Django 5.2.1 on 2025-05-16 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('numero_identificacion', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('rm_snatch', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rm_clean', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rm_deadlift', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rm_front_squat', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rm_back_squat', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rm_press_banca', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
