# Generated by Django 5.2.1 on 2025-05-16 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Completo')),
                ('numero_identificacion', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de Identificación')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('rm_snatch', models.FloatField(blank=True, null=True, verbose_name='RM Snatch (kg)')),
                ('rm_clean', models.FloatField(blank=True, null=True, verbose_name='RM Clean (kg)')),
                ('rm_deadlift', models.FloatField(blank=True, null=True, verbose_name='RM DeadLift (kg)')),
                ('rm_front_squat', models.FloatField(blank=True, null=True, verbose_name='RM Front Squat (kg)')),
                ('rm_back_squat', models.FloatField(blank=True, null=True, verbose_name='RM Back Squat (kg)')),
                ('rm_press_banca', models.FloatField(blank=True, null=True, verbose_name='RM Press de Banca (kg)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
