# Generated by Django 5.2.1 on 2025-09-25 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilusuario_delete_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='numero_identificacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Identificación'),
        ),
        migrations.AddConstraint(
            model_name='perfilusuario',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_identificacion__isnull', False)), fields=('numero_identificacion',), name='unique_numero_identificacion_when_not_null'),
        ),
    ]
