# Generated by Django 5.2.1 on 2025-09-25 19:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoWOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_wod', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del WOD')),
                ('categoria', models.CharField(choices=[('RX', 'RX'), ('Intermedio', 'Intermedio'), ('Principiante', 'Principiante')], max_length=12, verbose_name='Categoría')),
                ('tiempo_minutos', models.PositiveIntegerField(default=0, verbose_name='Minutos')),
                ('tiempo_segundos', models.PositiveIntegerField(default=0, verbose_name='Segundos')),
                ('repeticiones', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Repeticiones')),
                ('peso_total', models.FloatField(blank=True, null=True, verbose_name='Peso Total')),
                ('unidad_peso', models.CharField(choices=[('KG', 'Kilogramos (KG)'), ('LB', 'Libras (LB)')], default='KG', max_length=2, verbose_name='Unidad de Peso')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_wod', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultado de WOD',
                'verbose_name_plural': 'Resultados de WOD',
                'ordering': ['-fecha_wod', '-fecha_creacion'],
            },
        ),
    ]
