# Generated by Django 5.2.1 on 2025-09-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadowod',
            name='publico',
            field=models.BooleanField(default=True, help_text='Marcar si deseas que otros usuarios vean este resultado', verbose_name='¿Resultado público?'),
        ),
    ]
